"""
Canonical Repository Intelligence Model for Baton Phase 1.

This module defines the unified, structured representation of everything
Baton knows about a repository. All context generators and downstream
consumers must derive their output from this model — never from raw
repository files independently.

Evidence categories:
  DOCUMENTED  — explicitly stated in PRD/README/specification
  OBSERVED    — directly observed in source code/configuration/tests
  DERIVED     — mechanically established from observed relationships
  INFERRED    — reasonable interpretation, but not directly proven
  UNKNOWN     — could not be determined
  CONFLICTING — different sources disagree
  RECOMMENDED — a suggestion generated by Baton (never a fact)
"""

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class Confidence(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class EvidenceStatus(str, Enum):
    DOCUMENTED = "DOCUMENTED"
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    INFERRED = "INFERRED"
    UNKNOWN = "UNKNOWN"
    CONFLICTING = "CONFLICTING"
    RECOMMENDED = "RECOMMENDED"


class ImplementationStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    PARTIALLY_IMPLEMENTED = "PARTIALLY_IMPLEMENTED"
    IMPLEMENTED = "IMPLEMENTED"
    IMPLEMENTED_WITH_DIFFERENCES = "IMPLEMENTED_WITH_DIFFERENCES"
    NOT_DETECTABLE = "NOT_DETECTABLE"
    CONFLICTING = "CONFLICTING"
    UNKNOWN = "UNKNOWN"


class ProjectType(str, Enum):
    WEB_APPLICATION = "Web Application"
    FRONTEND = "Frontend Application"
    BACKEND_API = "Backend / API"
    FULL_STACK = "Full-Stack Application"
    MACHINE_LEARNING = "Machine Learning"
    DATA_SCIENCE = "Data Science"
    DATA_PIPELINE = "Data Pipeline"
    CLI = "CLI"
    LIBRARY_SDK = "Library / SDK"
    MOBILE = "Mobile"
    DESKTOP = "Desktop"
    GAME = "Game"
    EMBEDDED_IOT = "Embedded / IoT"
    AUTOMATION = "Automation"
    DEVOPS_INFRASTRUCTURE = "DevOps / Infrastructure"
    RESEARCH = "Research"
    SPECIFICATION_ONLY = "Documentation / Specification Only"
    MONOREPO = "Monorepo"
    MIXED_HYBRID = "Mixed / Hybrid"
    UNKNOWN = "Unknown"


class DirectoryRole(str, Enum):
    FRONTEND = "Frontend"
    BACKEND = "Backend / API"
    ML_PIPELINE = "ML Pipeline"
    DATA_PROCESSING = "Data Processing"
    CLI = "CLI"
    SHARED = "Shared / Domain Logic"
    TESTS = "Tests"
    CONFIGURATION = "Configuration"
    DOCUMENTATION = "Documentation"
    INFRASTRUCTURE = "Infrastructure / DevOps"
    ASSETS = "Assets / Static"
    GENERATED = "Generated / Build Output"
    EMBEDDED = "Embedded / Hardware"
    AMBIGUOUS = "Ambiguous / Mixed"
    UNKNOWN = "Unknown"


class SnapshotStatus(str, Enum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    PARTIAL = "PARTIAL"


# ---------------------------------------------------------------------------
# Evidence and classification primitives
# ---------------------------------------------------------------------------

@dataclass
class EvidenceSource:
    """A reference to the specific location supporting a claim."""
    file: str
    symbol: Optional[str] = None
    note: Optional[str] = None


@dataclass
class DetectedLanguage:
    name: str
    file_count: int
    extensions: list[str] = field(default_factory=list)
    evidence: list[str] = field(default_factory=list)
    confidence: Confidence = Confidence.MEDIUM


@dataclass
class DetectedTechnology:
    name: str
    category: str  # "framework", "build-tool", "testing", "database", "ml-framework", "cloud", etc.
    evidence: list[str] = field(default_factory=list)
    confidence: Confidence = Confidence.MEDIUM
    version: Optional[str] = None


@dataclass
class DirectoryClassification:
    path: str
    role: DirectoryRole
    confidence: Confidence
    evidence: list[str] = field(default_factory=list)
    # Future: user override layer preserving provenance
    user_override: Optional[str] = None
    observed_role: Optional[str] = None  # always the auto-detected role


@dataclass
class DocumentationSource:
    """A discovered documentation/specification file."""
    path: str
    role: str          # "PRD", "README", "ARCHITECTURE", "AGENTS", "RULES", "CONTRIBUTING", etc.
    headings: list[str] = field(default_factory=list)
    raw_excerpt: Optional[str] = None   # first 2000 chars only — never full file


@dataclass
class RepositoryRule:
    """A discovered instruction/rule from AGENTS.md, .builder, .cursor, etc."""
    source_path: str
    scope: str          # "repository-wide", "directory:<path>", "agent:<name>"
    rules: list[str] = field(default_factory=list)
    restrictions: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)


@dataclass
class ApiEndpoint:
    route: str
    method: str         # "GET", "POST", "PUT", "PATCH", "DELETE", "UNKNOWN"
    source_file: str
    callers: list[str] = field(default_factory=list)   # files that call this endpoint
    evidence: list[str] = field(default_factory=list)
    request_shape: Optional[str] = None
    response_shape: Optional[str] = None


@dataclass
class Requirement:
    """
    A single documented requirement or feature intent, compared against
    observed implementation.
    """
    id: str
    source_document: str
    source_section: Optional[str]
    intent: str
    status: ImplementationStatus = ImplementationStatus.UNKNOWN
    observed_code: list[str] = field(default_factory=list)
    missing_pieces: list[str] = field(default_factory=list)
    conflicts: list[str] = field(default_factory=list)
    evidence: list[str] = field(default_factory=list)
    confidence: Confidence = Confidence.LOW


@dataclass
class ArchitectureComponent:
    name: str
    role: str
    paths: list[str] = field(default_factory=list)
    responsibilities: list[str] = field(default_factory=list)
    dependencies: list[str] = field(default_factory=list)
    confidence: Confidence = Confidence.MEDIUM
    evidence: list[str] = field(default_factory=list)


@dataclass
class DataSource:
    path: str
    # "dataset", "fixture", "mock", "config", "model-artifact",
    # "training-artifact", "test-data", "seed", "generated", "static-data", "unknown"
    classification: str
    consumers: list[str] = field(default_factory=list)
    evidence: list[str] = field(default_factory=list)
    confidence: Confidence = Confidence.MEDIUM


@dataclass
class EnvVariable:
    name: str
    purpose: Optional[str] = None
    required: bool = False
    source_files: list[str] = field(default_factory=list)


@dataclass
class IntelligenceConflict:
    """
    A conflict between two sources of information.
    These must NEVER be silently merged.
    """
    description: str
    source_a: str       # e.g. "README.md"
    claim_a: str        # what source_a says
    source_b: str       # e.g. "requirements.txt"
    claim_b: str        # what source_b says
    resolution: str = "Not determinable automatically."


@dataclass
class ContextCompleteness:
    files_discovered: int = 0
    files_fully_analyzed: int = 0
    files_summarized: int = 0
    files_omitted: int = 0
    critical_files_omitted: int = 0
    omitted_paths: list[str] = field(default_factory=list)
    impact: str = "Unknown"
    status: str = "UNKNOWN"    # COMPLETE, PARTIAL, MINIMAL


# ---------------------------------------------------------------------------
# Canonical top-level model
# ---------------------------------------------------------------------------

@dataclass
class RepositoryIntelligence:
    """
    The single, authoritative, unified model of everything Baton has
    determined about a repository.

    This is the SOURCE OF TRUTH.
    All context generators must consume this model.
    No generator may independently re-inspect raw repository data.
    """

    # --- Snapshot identity ---
    owner: str
    repo: str
    branch: str
    commit: Optional[str]
    generated: str
    snapshot_status: SnapshotStatus = SnapshotStatus.CURRENT

    # --- Project identity ---
    project_types: list[ProjectType] = field(default_factory=list)
    project_type_evidence: list[str] = field(default_factory=list)
    project_summary: Optional[str] = None   # evidence-based description
    project_root: str = ""

    # --- Source-of-truth documents ---
    documentation_sources: list[DocumentationSource] = field(default_factory=list)
    repository_rules: list[RepositoryRule] = field(default_factory=list)

    # --- Languages and technologies ---
    languages: list[DetectedLanguage] = field(default_factory=list)
    technologies: list[DetectedTechnology] = field(default_factory=list)

    # --- Structure ---
    file_tree: list[dict] = field(default_factory=list)
    directory_classifications: list[DirectoryClassification] = field(default_factory=list)

    # --- Architecture ---
    components: list[ArchitectureComponent] = field(default_factory=list)
    data_flows: list[str] = field(default_factory=list)

    # --- API / interfaces ---
    api_endpoints: list[ApiEndpoint] = field(default_factory=list)

    # --- Requirements / features (DOCUMENTED vs OBSERVED) ---
    requirements: list[Requirement] = field(default_factory=list)
    observed_features: list[str] = field(default_factory=list)
    planned_features: list[str] = field(default_factory=list)

    # --- Data ---
    data_sources: list[DataSource] = field(default_factory=list)

    # --- Configuration ---
    env_variables: list[EnvVariable] = field(default_factory=list)
    config_files: list[str] = field(default_factory=list)

    # --- Deployment ---
    observed_deployment: list[str] = field(default_factory=list)
    planned_deployment: list[str] = field(default_factory=list)

    # --- Tests ---
    tests_detected: list[str] = field(default_factory=list)
    test_coverage_notes: list[str] = field(default_factory=list)

    # --- Conflicts / gaps / unknowns ---
    conflicts: list[IntelligenceConflict] = field(default_factory=list)
    unknowns: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    missing_work: list[str] = field(default_factory=list)
    analysis_warnings: list[str] = field(default_factory=list)

    # --- Coverage ---
    completeness: ContextCompleteness = field(default_factory=ContextCompleteness)

    # --- Backward-compatible legacy fields ---
    # These mirror the old RepositoryAnalyzer output so existing API consumers
    # and tests continue to work without modification.
    stack_detected: list[str] = field(default_factory=list)
    stack_languages: list[str] = field(default_factory=list)
    important_files: list[str] = field(default_factory=list)
    routes: list[str] = field(default_factory=list)
    api_calls: list[str] = field(default_factory=list)
    environment_variables: list[str] = field(default_factory=list)
    types: list[str] = field(default_factory=list)
    mock_data: list[str] = field(default_factory=list)
    handoffs: list[dict] = field(default_factory=list)
    shared_files: list[str] = field(default_factory=list)
    stray_files: list[str] = field(default_factory=list)

    def to_legacy_analysis(self) -> dict:
        """
        Produce a backward-compatible analysis dict matching the old
        RepositoryAnalyzer output shape. Used so existing API endpoints
        and frontend consumers continue to work unchanged.
        """
        return {
            "metadata": {
                "owner": self.owner,
                "repo": self.repo,
                "branch": self.branch,
                "folder": self.project_root,
                "commit": self.commit,
                "generated": self.generated,
                "files_analyzed": self.completeness.files_fully_analyzed,
                "skipped_files": self.completeness.omitted_paths,
            },
            "stack": {
                "detected": self.stack_detected,
                "languages": self.stack_languages,
            },
            "file_tree": self.file_tree,
            "important_files": self.important_files,
            "routes": self.routes,
            "api_calls": self.api_calls,
            "environment_variables": self.environment_variables,
            "types": self.types,
            "mock_data": self.mock_data,
            "handoffs": self.handoffs,
            "shared_files": self.shared_files,
            "stray_files": self.stray_files,
            "analysis_warnings": self.analysis_warnings,
        }
