import type { WorkspaceStateHook } from '@/hooks/useWorkspaceState';
import { useSyncExternalStore } from 'react';
import { getUsage, subscribeUsage, type Counts } from '@/lib/usage';
const operationName = (operation: string) => ({'/api/v1/analysis/repository': 'Repository analysis', '/api/v1/analysis/folder': 'Folder analysis', '/api/v1/github/validate-repository': 'Repository validation', '/api/v1/github/access': 'Access check', '/api/v1/github/branches': 'Branches', '/api/v1/github/tree': 'Tree', '/api/v1/github/file': 'File preview', '/api/v1/workspace/source': 'Pinned source', '/api/v1/workspace/chat': 'Chat', '/api/v1/workspace/inspect': 'Workspace readiness', '/api/v1/workspace/provider/validate': 'Gemini validation', '/api/v1/workspace/artifacts': 'Artifact', '/api/v1/workspace/compare': 'Branch comparison', '/api/v1/context': 'Working context', '/api/v1/integration': 'Integration check', '/api/v1/conflicts': 'Conflict inventory'} as {[key:string]:string})[operation] || 'Baton operation';
const value = (count: number | null | undefined) => count == null ? 'UNKNOWN' : count.toLocaleString();
function AIUsage({ label, counts }: { label: string; counts: Counts }) {
  return <section className="border-t border-baton-border py-6" aria-label={label}>
    <h2 className="text-lg mb-4">{label}</h2>
    <dl className="grid grid-cols-2 gap-3 text-sm">
      {([['AI requests', counts.ai_requests], ['Input tokens', counts.input_tokens], ['Output tokens', counts.output_tokens], ['Total tokens', counts.total_tokens], ['Thinking tokens', counts.thinking_tokens], ['Average provider latency (ms)', counts.provider_latency_ms !== null && counts.ai_requests ? Math.round(counts.provider_latency_ms / counts.ai_requests) : counts.ai_requests === 0 ? 0 : null], ['Errors', counts.errors], ['Abandoned operations', counts.abandoned]] as const).map(([name, count]) => <div key={name}><dt className="text-baton-text-tertiary">{name}</dt><dd>{value(count)}</dd></div>)}
    </dl>
  </section>;
}
export function UsageCenter({ state }: { state: WorkspaceStateHook }) {
  const { session, conversation, quota, last, lastGithub, githubOperations } = useSyncExternalStore(subscribeUsage, getUsage);
  return <div className="p-6 lg:p-10 max-w-4xl mx-auto">
    <h1 className="text-2xl mb-3">Usage Center</h1>
    <p className="text-sm text-baton-text-tertiary mb-6">This tab's runtime session. Reload clears measurements. New Chat clears the current conversation totals and preserves session totals. UNKNOWN means the provider or backend did not report a measurement.</p>
    <p className="text-sm mb-4">Provider: Gemini · Model: {state.geminiModel || 'UNKNOWN'} · {state.geminiReady ? 'Key/model metadata validated' : 'AI not validated'}</p>
    <AIUsage label="Current conversation" counts={conversation} />
    <AIUsage label="Current Baton session" counts={session} />
    <section className="border-t border-baton-border py-6"><h2 className="text-lg mb-4">Baton GitHub consumption</h2><dl className="grid grid-cols-2 gap-3 text-sm">
      {([['API requests', session.github_requests], ['Successful requests', session.github_successes], ['Failed requests', session.github_failures], ['Rate-limited requests', session.github_rate_limited], ['Coalesced reads', session.coalesced], ['Files collected', session.files_collected], ['Archive downloads', session.github_downloads], ['Cache hits', session.cache_hits], ['Snapshot reads', session.snapshot_hits]] as const).map(([name, count]) => <div key={name}><dt className="text-baton-text-tertiary">{name}</dt><dd>{value(count)}</dd></div>)}
    </dl><p className="text-xs text-baton-text-tertiary mt-4">Downloads are counted separately from GitHub API requests. Reusing evidence does not collect repository files again; authorization can still read HEAD.</p></section>
    <section className="border-t border-baton-border py-6"><h2 className="text-lg mb-4">GitHub provider quota</h2><p className="text-sm">Authentication: {state.githubToken && state.repo?.authenticated ? 'Authenticated' : 'Not authenticated'}.<br />Latest observed account bucket: {value(quota.remaining)} remaining / {value(quota.limit)} limit. Used: {value(quota.used)}. Reset: {quota.reset_at ? new Date(quota.reset_at * 1000).toLocaleString() : 'UNKNOWN'}. Resource: {quota.resource || 'UNKNOWN'}.</p><p className="text-xs text-baton-text-tertiary mt-3">Shared account quota is separate from this tab's Baton consumption. Gemini token counts are provider reports, not character estimates, monetary charges or remaining account quota. Deterministic exports make zero AI calls. Abandoning a browser request does not prove remote cancellation.</p></section>
    <section className="border-t border-baton-border py-6"><h2 className="text-lg mb-3">GitHub request breakdown</h2><dl className="grid grid-cols-2 gap-3 text-sm">{Object.entries(githubOperations).map(([operation, count]) => <div key={operation}><dt>{({repository: 'Repository validation / metadata', access: 'Access check', branches: 'Branches', commit: 'HEAD / commit', tree: 'Tree', file: 'Files / source', archive: 'Analysis archive'} as {[key: string]: string})[operation]}</dt><dd>{value(count)}</dd></div>)}</dl><p className="text-xs text-baton-text-tertiary mt-3">Actual upstream requests, including those used by analysis, source, conflict scans, integration and comparison. Empty breakdown means no reported requests. Gemini validation requests: {value(session.ai_validation_requests)}; these do not generate content.</p></section>
    {lastGithub && <section className="border-t border-baton-border py-6" aria-label="Last GitHub operation"><h2 className="text-lg mb-3">Last GitHub operation</h2><code className="text-xs break-all">{operationName(lastGithub.operation)}</code><p className="text-sm mt-2">Requests: {value(lastGithub.github_requests)} · Cache hits: {value(lastGithub.cache_hits)} · Files collected: {value(lastGithub.files_collected)} · {value(lastGithub.latency_ms)} ms · Snapshot: {lastGithub.snapshot_created === null ? 'UNKNOWN' : lastGithub.snapshot_created ? 'Created' : lastGithub.snapshot_hits ? 'Reused' : 'No creation reported'}</p></section>}
    {last && <section className="border-t border-baton-border py-6" aria-label="Last operation"><h2 className="text-lg mb-3">Last operation</h2><code className="text-xs break-all">{operationName(last.operation)}</code><p className="text-sm mt-2">Status: {last.abandoned ? 'Abandoned by browser' : last.status || 'Network error'} · {value(last.latency_ms)} ms</p></section>}
  </div>;
}
