// Opt-in production acceptance, real GitHub and no mocked APIs. Stops honestly at unavailable Gemini.
const assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.BATON_PLAYWRIGHT_PATH||'playwright');let browser,token='';
(async()=>{
 const credential=execFileSync('git',['credential','fill'],{input:'protocol=https\nhost=github.com\n\n',encoding:'utf8',stdio:['pipe','pipe','pipe'],env:{...process.env,GIT_TERMINAL_PROMPT:'0',GCM_INTERACTIVE:'Never'}});token=credential.split(/\r?\n/).find(line=>line.startsWith('password='))?.slice(9)||'';assert(token);
 browser=await chromium.launch({executablePath:process.env.BATON_BROWSER_PATH,headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});const observations=[],checks=[],jobs=[];
 page.on('response',res=>{const p=new URL(res.url()).pathname;if(p.startsWith('/api/v1/'))jobs.push((async()=>{const record={operation:p,status:res.status(),usage:JSON.parse(await res.headerValue('x-baton-usage')||'null')};if(p.endsWith('/inspect')){const data=await res.json();record.provider=data.provider;record.state=data.state;record.identity=data.identity;}observations.push(record);})());});
 await page.goto('https://baton-sigma-six.vercel.app/?phase3_revision='+process.env.BATON_EXPECT_REVISION);const revision=await page.locator('meta[name="baton-revision"]').getAttribute('content');
 assert.equal(revision,process.env.BATON_EXPECT_REVISION,'Frontend rollout not yet current');
 await page.getByRole('button',{name:/Enter Mission Control/}).first().click();await page.getByRole('button',{name:'Repository',exact:true}).click();await page.getByPlaceholder('https://github.com/owner/repository').fill('https://github.com/octocat/Hello-World');await page.getByLabel('Fine-grained GitHub token').fill(token);await page.getByRole('button',{name:'CONNECT REPOSITORY',exact:true}).click();
 await page.getByLabel('GitHub token for connected repository').waitFor({timeout:90000});await page.getByRole('button',{name:'AI workspace',exact:true}).click();await page.locator('.ai-refresh:not(:disabled)').waitFor({timeout:90000});await page.locator('.ai-refresh').click();await page.waitForFunction(()=>document.querySelector('.ai-grounding')?.textContent==='Repository grounded',null,{timeout:120000});await page.locator('.ai-refresh:not(:disabled)').waitFor();
 checks.push('Deployed frontend -> Render -> accepted user GitHub credential -> explicit analysis -> valid commit snapshot');
 await Promise.all(jobs);const snapshot=observations.filter(record=>record.operation.endsWith('/inspect')&&record.state==='READY').at(-1);assert(snapshot);
 const before=observations.filter(record=>record.operation.endsWith('/inspect')||record.operation.includes('/analysis/')).length;await page.getByRole('button',{name:'New chat',exact:true}).click();await Promise.all(jobs);assert.equal(observations.filter(record=>record.operation.endsWith('/inspect')||record.operation.includes('/analysis/')).length,before);checks.push('Production New Chat causes zero analysis/inspection requests');
 if(!snapshot.provider.configured){assert(await page.getByLabel('Ask about the connected repository').isDisabled());checks.push('Missing Gemini configuration is explicit; no fake provider answer and disabled composer');}
 await page.getByRole('button',{name:'Generate artifact',exact:true}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Context Builder',exact:true}).click();await page.getByRole('button',{name:'GENERATE CONTEXT',exact:true}).click();await page.getByRole('button',{name:'COPY',exact:true}).waitFor();checks.push('Production deterministic artifact/hash preview and canonical Context Builder succeed without Gemini');
 await page.getByRole('button',{name:'Usage Center',exact:true}).click();await page.getByRole('heading',{name:'Usage Center',exact:true}).waitFor();checks.push('Usage Center is deployed with separate provider quota and Baton consumption');
 await page.getByRole('button',{name:'Repository',exact:true}).click();await page.getByText('README',{exact:true}).click();await page.waitForFunction(()=>document.querySelector('pre')?.textContent?.includes('Hello World'));checks.push('Actual repository source is readable');
 await page.getByRole('button',{name:'AI workspace',exact:true}).click();const branch=page.getByLabel('Current repository branch'),current=await branch.inputValue(),other=await branch.locator('option').evaluateAll((options,active)=>options.map(o=>o.value).find(value=>value&&value!==active),current);
 if(other){await branch.selectOption(other);await page.locator('.ai-refresh:not(:disabled)').waitFor({timeout:90000});assert(await page.getByLabel('Ask about the connected repository').isDisabled());checks.push('Production branch switch blocks missing/stale snapshot');}
 await page.getByRole('button',{name:'Change repository',exact:true}).click();await page.getByLabel('Fine-grained GitHub token').waitFor();checks.push('Production repository switch clears previous connection');
 await Promise.all(jobs);const report={status:'passed',revision,liveGemini:'UNVERIFIED',provider:snapshot.provider,identity:snapshot.identity,fineGrainedCredential:token.startsWith('github_pat_'),checks,observations};fs.writeFileSync(path.join(__dirname,'../.test-output/phase3-production-result.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,observations:undefined},null,2));
})().catch(error=>{console.error(String(error.message||error).split(token||'\0').join('[REDACTED]'));process.exitCode=1;}).finally(async()=>{await browser?.close();token='';});
