const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { createHash } = require('node:crypto');
const { chromium } = require(process.env.BATON_PLAYWRIGHT_PATH || 'playwright');
const fixture = JSON.parse(fs.readFileSync(path.join(__dirname, '../.test-output/workspace-fixtures.json'), 'utf8'));
const checks = [], calls = [], errors = [];
let browser;
(async () => {
 browser = await chromium.launch({ executablePath: process.env.BATON_BROWSER_PATH, headless: true });
 const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true });
 const page = await context.newPage(); page.on('pageerror', e => errors.push(e.message));
 await context.route(/\/api\/(?:v1\/|health(?:$|\?))/, async route => {
  const req = route.request(), url = new URL(req.url());
  const body = req.method() === 'POST' ? req.postDataJSON() || {} : {};
  calls.push({ path: url.pathname, body });
  let result;
  if (url.pathname.endsWith('/branches')) result = { branches: [{ name: 'main', sha: fixture.project.identity.commit }] };
  else if (url.pathname.endsWith('/inspect')) result = fixture.project;
  else if (url.pathname.endsWith('/context')) result = { analysis: fixture.analysis, context: { identity: fixture.project.identity }, markdown: 'Canonical briefing for requested task', estimated_tokens: 100, omitted: [] };
  else if (url.pathname.endsWith('/artifacts')) {
   const content = `# ${body.artifact_type}\nRepository example/project; snapshot ${fixture.project.identity.commit}`;
   result = { ...fixture.artifact, artifact_type: body.artifact_type, content, filename: `${body.artifact_type}.md`, sha256: createHash('sha256').update(content).digest('hex') };
  } else if (url.pathname.endsWith('/prompt')) result = { prompt: `USER_PROVIDED manual input for ${body.repository}` };
  else if (url.pathname.endsWith('/integration')) result = { status: 'analyzed', comparison: { frontend_routes: [], backend_routes: [], unmatched_frontend_routes: [], unmatched_backend_routes: [], compatible: null, evidence_status: 'insufficient' } };
  else result = { status: 'ok' };
  await route.fulfill({ json: result });
 });
 await page.addInitScript(() => {
  if (!localStorage.getItem('baton-workspace-state')) localStorage.setItem('baton-workspace-state', JSON.stringify({ repo: { owner: 'example', repository: 'project', accessible: true }, selectedBranch: 'main', selectedFolder: '', isDemoMode: false, members: [] }));
 });
 await page.goto(process.env.BATON_PREVIEW_URL || 'http://localhost:5173/');
 await page.getByRole('button', { name: /Enter Mission Control/i }).first().click();
 await page.getByRole('button', { name: /Team.*Ownership/ }).click();
 await page.getByRole('button', { name: 'ADD MEMBER', exact: true }).click();
 await page.getByLabel('Member Name', { exact: true }).fill('Maya');
 await page.getByLabel('Role', { exact: true }).fill('Frontend');
 await page.getByLabel('Folders (comma-separated)', { exact: true }).fill('client/');
 await page.getByLabel('Do not touch (comma-separated)', { exact: true }).fill('server/');
 await page.getByRole('button', { name: 'SAVE MEMBER', exact: true }).click();
 await page.getByLabel('Edit Maya', { exact: true }).click();
 await page.getByLabel('Role', { exact: true }).fill('Frontend lead');
 await page.getByRole('button', { name: 'SAVE MEMBER', exact: true }).click();
 await page.getByText('Frontend lead', { exact: true }).waitFor();
 let stored = await page.evaluate(() => JSON.parse(localStorage.getItem('baton-workspace-state')));
 assert.equal(stored.members.length, 1); assert.equal(stored.members[0].role, 'Frontend lead');
 const memberId = stored.members[0].id;
 await page.reload();
 await page.getByRole('button', { name: /Enter Mission Control/i }).first().click();
 await page.getByRole('button', { name: /Team.*Ownership/ }).click();
 await page.getByText('Frontend lead', { exact: true }).waitFor();
 checks.push('Team add/edit survives reload without duplicating identity');
 await page.getByRole('button', { name: 'Context Builder', exact: true }).click();
 await page.getByRole('button', { name: 'GENERATE CONTEXT', exact: true }).click();
 await page.getByText('Canonical briefing for requested task', { exact: true }).waitFor();
 await page.getByLabel('Purpose / Task').fill('Fix Ask Book UI');
 await page.getByLabel('Target teammate', { exact: true }).selectOption(memberId);
 await page.getByLabel('Context type', { exact: true }).selectOption('role');
 await page.getByLabel('Context constraints').fill('Keep the current API');
 await page.getByLabel('Context budget').fill('4096');
 await page.getByRole('button', { name: 'GENERATE CONTEXT', exact: true }).click();
 await page.getByText('Canonical briefing for requested task', { exact: true }).waitFor();
 const generated = calls.filter(c => c.path.endsWith('/context')).at(-1).body;
 assert.equal(generated.max_bytes, 16384); assert.equal(generated.task, 'Fix Ask Book UI'); assert.equal(generated.context_type, 'role');
 assert.deepEqual(generated.member.ownership, ['client/']); assert.deepEqual(generated.member.do_not_touch, ['server/']); assert.deepEqual(generated.constraints, ['Keep the current API']);
 checks.push('Context task/type/member/budget/constraints reach existing API');
 await page.getByRole('button', { name: 'Prompt Builder', exact: true }).click();
 await page.getByLabel('Prompt task', { exact: true }).fill('Fix Ask Book UI');
 await page.getByLabel('Prompt teammate', { exact: true }).selectOption(memberId);
 await page.getByRole('button', { name: 'BUILD PROMPT', exact: true }).click();
 await page.getByText(/Repository example\/project; snapshot/).waitFor();
 assert.equal(calls.filter(c => c.path.endsWith('/artifacts')).at(-1).body.member.name, 'Maya');
 assert.equal(calls.filter(c => c.path.endsWith('/prompt')).length, 0);
 await page.getByLabel('Prompt evidence source').selectOption('manual');
 await page.getByRole('button', { name: 'BUILD PROMPT', exact: true }).click();
 await page.getByText(/USER_PROVIDED manual input for example\/project/).waitFor();
 checks.push('Canonical prompt uses snapshot artifact; manual prompt is marked unverified');
 await page.getByRole('button', { name: 'Overview', exact: true }).click();
 await page.getByText('SNAPSHOT IDENTITY', { exact: true }).waitFor();
 assert(!await page.getByText('84', { exact: true }).count());
 assert(!await page.getByText('3.2K TOKENS', { exact: true }).count());
 await page.getByText(String(fixture.project.completeness.files_analyzed), { exact: true }).waitFor();
 checks.push('Overview shows measured coverage and snapshot identity');
 await page.getByRole('button', { name: 'Integration', exact: true }).click();
 await page.getByPlaceholder('member/maya-ui').fill('main');
 await page.getByPlaceholder('member/arjun-api').fill('main');
 await page.getByRole('button', { name: /CHECK INTEGRATION/ }).click();
 await page.getByText('INSUFFICIENT API EVIDENCE', { exact: true }).waitFor();
 checks.push('Empty integration evidence cannot display ready');
 await page.getByRole('button', { name: /Team.*Ownership/ }).click();
 await page.getByLabel('Delete Maya', { exact: true }).click();
 stored = await page.evaluate(() => JSON.parse(localStorage.getItem('baton-workspace-state')));
 assert.equal(stored.members.length, 0); checks.push('Team delete persists');
 assert.equal(calls.filter(c => c.path.includes('/analysis/')).length, 0, 'Projection tools must not rescan');
 await page.getByRole('button', { name: 'AI workspace', exact: true }).click();
 await page.getByRole('button', { name: /Project scope/ }).click();
 await page.getByLabel('Explicit task', { exact: true }).fill('Review Ask Book UI');
 await page.getByRole('button', { name: 'Apply scope', exact: true }).click();
 await page.getByRole('button', { name: 'Refresh analysis', exact: true }).waitFor();
 for (const [type, title] of Object.entries({ context: 'Repository context', handoff: 'Developer handoff', prd: 'PRD evidence draft', technical_design: 'Technical design', tasks: 'Task breakdown', onboarding: 'Developer onboarding', implementation_plan: 'Implementation plan', review: 'Review briefing', prompt: 'Coding prompt' })) {
  await page.getByLabel('Artifact type', { exact: true }).selectOption(type);
  await page.getByRole('button', { name: 'Generate artifact', exact: true }).click();
  await page.getByRole('dialog', { name: title, exact: true }).waitFor();
  const downloaded = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download', exact: true }).click();
  assert.equal((await downloaded).suggestedFilename(), `${type}.md`);
  await page.keyboard.press('Escape');
 }
 checks.push('All nine artifact types verify hashes, preview and download without analysis');
 assert.equal(calls.filter(c => c.path.includes('/analysis/')).length, 0);
 await page.getByRole('button', { name: 'Open workspace settings', exact: true }).click();
 await page.getByLabel(/Baton access key/).fill('test-operator-key');
 assert(!await page.evaluate(() => JSON.stringify(localStorage).includes('test-operator-key')));
 await page.getByRole('button', { name: 'Reset local workspace', exact: true }).click();
 await page.getByText('No repository connected', { exact: true }).first().waitFor();
 stored = await page.evaluate(() => JSON.parse(localStorage.getItem('baton-workspace-state')));
 assert.equal(stored.repo, null); assert.deepEqual(stored.members, []);
 assert(!('batonAccessKey' in stored) && !('githubToken' in stored));
 assert.equal(await page.locator('.ai-artifact-item').count(), 0);
 checks.push('Settings key stays in memory; reset clears repository, team and artifact state');
 assert.deepEqual(errors, []);
 console.log(`Product completion browser checks: ${checks.length} passed.\n${checks.join('\n')}`);
 await browser.close();
})().catch(async error => { console.error(error.message); if (browser) await browser.close(); process.exitCode = 1; });
